import numpy as np

import statsmodels.stats.inter_rater as irr

ratings_raw = np.array([
    [1, 1, 0, 1, 0], # "Glumice koje su u jednom periodu svoje karijere odlučile stati iza kamere te se tako okušati kao redateljice nisu rijetkost u svijetu filma."
    [1, 1, 0, 1, 0], # "Sjetimo se samo Maggie Gyllenhaal i filma 'The Lost Daughter', adaptaciji istoimenog romana, nominiranog za čak tri Oscara."
    [0, 0, 0, 0, 0], # "Zasigurno jedan od najboljih primjera je i Sofia Coppola sa svojim sad već kultnim filmom 'The Virgin Suicides', dok je najsvježija glumačko – redateljska priča svakako ona Grete Gerwig koja je s debitantskim filmom 'Lady Bird' pokazala sav svoj talent koji je kasnije još više potvrdila s 'Little Women' i posebice 'Barbie'."
    [0, 0, 1, 0, 0], # "Meni je posebno drag film 'Booksmart', redateljski debi Olivije Wilde, jednako kao i 'One Night in Miami', Regine King."
    [0, 0, 0, 0, 0], # "Naravno, lista je kudikamo veća, što dovoljno govori u prilog tome kako se iza glumica često kriju redateljski talenti koji samo čekaju da isplivaju na filmsku površinu."
    [1, 0, 0, 0, 0], # "Jedan od takvih talenata otkrio se kroz lik i djelo glumice Anne Kendrick, najpoznatije po ulozi u filmu 'Up in the Air' za koju je nominirana i za Oscara u kategoriji najbolje sporedne glumice."
    [1, 1, 0, 1, 1], # "Anna je kao glumica debitirala u filmu 'Camp', da bi se sada, evo nešto više od dvadeset godina od glumačkog, odlučila i za onaj redateljski, i to s filmom 'Woman of the Hour'."
    [1, 1, 0, 1, 1], # "Postoji puno datuma koji su obilježili povijest televizije."
    [1, 1, 0, 1, 1], # "Jedan od njih je inspirirao film 'Woman of the Hour', a dogodio se 13. rujna 1978. godine kada se u popularnoj igri za spajanje parova, 'The Dating Game', pojavio natjecatelj pod imenom Rodney Alcala."
    [1, 1, 0, 1, 1], # "Kasnije će se uspostaviti kako je upravo taj lik, a koji je, da bi stvar bila još čudnija, i pobijedio u toj emisiji, zapravo seksualni predator i serijski ubojica."
    [0, 0, 0, 0, 0], # "Kendrick je ovoj mračnoj temi kroz krimi žanr pristupila na drugačiji način nego što inače viđamo kada su u pitanju priče o serijskim ubojicama."
    [1, 1, 0, 0, 0], # "Naime, Kendrick ni u jednom trenutku ne humanizira Alcalu, već je fokus na njegovim žrtvama."
    [1, 0, 0, 0, 0], # "Također, nju ne zanimaju njegovi motivi ili pozadinska priča, čime izbjegava romantiziranje lika, već je više usredotočena na jasnu osudu protiv mizoginije, rodne nejednakosti, seksualnog omalovažavanja i objektiviziranja žena, a što je duboko ukorijenjeno u suvremenom društvu, počevši od običnih radnih mjesta pa sve do blještavila Hollywooda."
    [0, 0, 1, 0, 0], # "Women of the Hour tako postaje dobro strukturirani triler koji se uspješno bavi složenijim i bitnim temama."
    [0, 0, 0, 0, 0], # "Uvodna scena na neki način služi s upoznavanjem tona filma, i to kroz tople boje, psihodelije, spore naracije i napetog tempa."
    [1, 1, 0, 1, 1], # "Kendrick koristi četiri ključne razine priče."
    [1, 1, 0, 1, 0], # "U prvoj gledamo glavnu junakinju Sheryl, i to upravo u izvedbi Anne Kendrick koja je tako u dvostrukoj ulozi, glumice i redateljice."
    [1, 1, 0, 1, 0], # "Sheryl je u filmu mlada glumica u potrazi za slavom, a gdje ćeš boljeg mjesta za ostvarivanje snova od Los Angelesa."
    [1, 0, 1, 0, 0], # "Međutim, grad snova Kendrick prikazuje kakav on često i jest, mračan i okrutan, i to kroz temu filma koja se savršeno uklapa upravo u takav ton."
    [1, 0, 0, 0, 0], # "U drugoj razini vidimo Rodneya Alcalu (jako dobar Daniel Zovatto), i to isključivo kroz način na koji je mamio svoje žrtve."
    [1, 1, 1, 1, 1], # "Treći dio priče nas vodi u samu emisiju za spajanje parova u kojoj se Alcala prijavio i u kojoj je izabran kao 'savršen partner', dok se u četvrtoj i završnoj upoznajemo s ključnim i fatalnim susretom koji je na više razina simboličan i kroz koji Kendrick savršeno poentira poruku koju je željela poslati."
    [2, 2, 2, 2, 2], # "Film ima sugestivnu fotografiju koja nas na prvi pogled može odvesti na krivi trag."
    [1, 1, 2, 0, 0],  # "Takve tople boje bi više odgovarale nekom 'feel good' filmu, pa je u tom pogledu jasno kako Kendrick ima drugačiji pogled na krimi žanr."
    [1, 1, 1, 1, 1],  # "Ne samo da ne pokazuje pretjerani interes za ubojičine motive, već koristi slike prirode kroz koje stvara našu veću povezanost sa žrtvama od trenutka kada ih upoznajemo."
    [1, 1, 1, 1, 1],  # "Tako kao da nam želi poručiti kako su one puno veće i bitnije, baš kao i priroda koja ih okružuje, od čovjeka kojeg su imale nesreću sresti."
    [0, 0, 1, 0, 1],  # "Vizualna disciplina koju je Kendrick pokazala kroz film uistinu je impresivna jer je uspjela postići ljepotu i u smrti."
    [0, 0, 1, 0, 1],  # "Ljepota Kendrickinog filma dolazi upravo od žena, njihovog okruženja i izvedbi u tim životnim trenucima kojima svjedočimo."
    [0, 0, 0, 1, 1],  # "Priroda kao da postaje sinonim prkosa, onog istog kojeg su žrtve pokazale prema ubojici."
    [0, 0, 1, 0, 1],  # "I bez obzira na to što imamo ograničeno vrijeme da ih upoznamo, prostor u kojem ih stavlja redateljica dovoljno govori o složenosti njihovih života."
    [0, 0, 0, 1, 1],  # "Ljepota okruženja kao prikaz ljepote cijelog života žena koje su imale i koji na takav način i dalje živi."
    [0, 0, 1, 0, 1],  # "Prikaz seksizma kroz krimi žanr, posebice kada je riječ o istinitim pričama nije baš lagan zadatak, no Kendrick pokazuje kako mu je itekako dorasla."
    [0, 0, 1, 0, 1],  # "U tom pogledu njeno najjače oružje postaje suptilnost koja djeluje poput malih tragova koje nažalost neće svatko prepoznati."
    [1, 1, 1, 1, 2],  # "Kao najbolji dokaz ovoj mojoj tvrdnji svakako treba izdvojiti sporedne likove koji samo na prvi pogled nemaju veze s centralnom radnjom filma."
    [1, 1, 0, 1, 2],  # "Oni možda nisu serijski ubojice, ali su u osnovi tipovi koje susrećete na poslu, ulici, danas i na društvenim mrežama."
    [0, 0, 1, 0, 1],  # "I u tome Kendrick izvrsno poentira kroz neozbiljnost koja je pokazana prilikom hvatanja serijskog ubojice u filmu."
    [0, 0, 1, 0, 1],  # "Psihološki triler žanrovski uspijeva uhvatiti emociju žrtava."
    [1, 1, 1, 1, 1],  # "Jer ovdje nije važno što se događa u mračnom umu ubojice već je fokus na tuzi koju osjećamo gledajući sve te žene."
    [1, 1, 1, 1, 1],  # "Pri tome je jako zanimljivo promatrati njihove reakcije u određenim momentima."
    [1, 1, 1, 1, 1],  # "Jer, sloboda i moć koju možda i osjete, ponekad treba biti zatvorena i smanjena, i to od njih samih."
    [1, 1, 1, 1, 1],  # "Dakako da bismo svi voljeli vidjeti kako se one s lakoćom obračunavaju ne samo s ubojicom već i sa svim problemima."
    [0, 0, 1, 0, 1],  # "Seksistička dinamika moći izvrsno se koristi za stvaranje napetosti u filmu."
    [1, 1, 1, 1, 0],  # "Referenta točka kada je u pitanju neprikazivanje nasilja svakako je film 'Nema zemlje za starce', braće Cohen."
    [1, 1, 1, 1, 0],  # "Jer publika je ta koja koristi svoju maštu, a što omogućuje filmu manje eksplicitnosti kako radnja odmiče."
    [1, 1, 1, 1, 1],  # "Mi samo čujemo što se događa, a mašta je uvijek gora od svega onoga što se može pokazati ili staviti na ekran."
    [1, 1, 0, 1, 1],  # "Emocija je dakle u onome što se događa, a ne u prikazu užasa."
    [1, 1, 1, 1, 1],  # "Pa ipak, bilo bi pogrešno reći kako na film ne vodi u istraživanje i ubojičinog načina razmišljanja."
    [1, 1, 1, 1, 1],  # "No, u suštini, odgovori koje tražimo fokusiraju se više na društveni utjecaj, a ne na samog ubojicu i njegove postupke."
    [1, 1, 0, 1, 0],  # "Prema njemu nemamo nikakvo zanimanje jer on ni po čemu nije poseban."
    [0, 0, 1, 0, 0],  # "I zato mislim kako je pun pogodak što film uopće nije zainteresiran za ispitivanje onoga što tjera ubojicu na ono što radi."
    [1, 1, 0, 1, 0], # "Jer Alcala nije izmicao pravdi zato što je nešto posebno inteligentan i briljantan, već jer je tadašnje društvo svojim ponašanjem neposredno u mnogočemu i bilo na njegovoj strani."
    [1, 1, 0, 1, 1], # "Women of the Hour je film koji se u velikom dijelu oslanja na neverbalne znakove."
    [1, 1, 2, 1, 2], # "Pravo je pitanje samo hoće li to biti dovoljno da društvo napokon prepozna upravo kroz običan pogled tko su zapravo tihe “serijske ubojice” ili će odmahnuti glavom."
    [0, 0, 1, 1, 0], # "Postoji u filmu jedna odlična scena kada se glavna junakinja nađe na praznom parkingu s ubojicom, a koja po meni savršeno oslikava cijeli film."
    [1, 1, 0, 1, 2], # "Sve stane u jednu šetnju. Šetnju izbora i šetnju (ne)sreće koju osjeti i živi jako puno žena."
    [1, 1, 1, 1, 2], # "I to ne samo dok šetaju same po mraku, ako se za takvo nešto uopće i usude."
    [0, 0, 1, 0, 0], # "Film kao takav, osim što je žanrovski uspješan, itekako je bitan i važan, i to kao poticaj za puno širi razgovor o temama koje se prečesto uzimaju zdravo za gotovo."
    [1, 1, 1, 1, 1], # "Jednako kao što je to bio slučaj s Rodneyjem Alcalom."
    [2, 2, 2, 2, 2], # "Nažalost."
    [0, 0, 0, 0, 0], # "Ostavlja bez daha."
    [1, 1, 2, 1, 0], # "Mislim kako mi nikad nije trebalo duže vremena da započnem pisanje recenzije kao što je to slučaj s filmom „Dune: Part Two“, redatelja Denisa Villeneuvea."
    [0, 0, 1, 0, 0], # "Buljim, evo sad već dobrih dvadesetak minuta ispred praznog papira, razmišljajući kako opisati film koji me, baš kako bi rekao Paul, gledajući prostranstva pješčanog planeta, ostavio bez daha."
    [0, 0, 1, 0, 0], # "I uistinu, ne sjećam se kada mi se dogodilo da uopće ne mogu sastaviti suvisle rečenice s kojima bih, barem donekle, opisao ono što sam osjećao prilikom izlaska iz kina."
    [1, 1, 0, 0, 2], # "Siguran sam kako sam unaprijed osuđen na poraz kada je u pitanju vjerno prenošenje dojmova filma i to naprosto zato što smatram kako je to nemoguća misija, no barem se mogu potruditi da vam približim barem djelić onoga što sam osjećao prilikom doživljaja na velikom platnu."
    [0, 0, 0, 0, 0], # "Jer, ruku na pijesak, ovo i jest film koji se gleda i osjeća."
    [1, 1, 1, 1, 1], # "Paradoksa radi, koliko god se veselilo svemu vezano uz filmsku adaptaciju romana jednog od najvećih pisaca svih vremena, Franka Herberta, istovremeno sam osjećao dozu neizvjesnosti s obzirom na to da je film „Dune“ na neki način postao glasnik loših vijesti."
    [2, 2, 0, 2, 2], # "Sjetimo se samo odgađanja premijere prvog filma zbog pandemije, da bi zatim i drugi dio zadesila ista sudbina zbog štrajka scenarista."
    [1, 1, 0, 1, 2], # "Dakle, treba dobro pripaziti ako nam stigne najava trećeg filma."
    [1, 0, 1, 0, 0], # "Pa ipak, unatoč neizvjesnosti za budućnost kina, pardon, planeta Arrakis, napokon smo dočekali nastavak filma koji nas je oduševio prije tri godine."
    [0, 0, 0, 0, 0], # "Najbitnije od svega svakako je činjenica što je i ovaj put „redateljskog crva“ zajahao Denis Villeneuve, jedan od najboljih redatelja današnjice."
    [0, 0, 1, 0, 0], # "Razlog optimizma leži u tome što je upravo Villeneuvea adaptacija, uz poseban naglasak na adaptacija, na najbolji mogući način očuvala duh, poeziju, atmosferu, boju i miris svega onoga što je Herbert zapisao kroz svoje romane."
    [1, 1, 1, 1, 1], # "Koliko je teško osvojiti pijesak Dine, najbolje znaju redatelji David Lynch i Alejandro Jodorowsky, a čije su (ne)ispunjene ambicije progutale svaku nadu za bilo kojeg filmaša koji je uopće i pomislio zajahati crva."
    [0, 1, 1, 1, 0], # "Pa ipak, Denis Villeneuve pokazao je kako voli izazove."
    [0, 0, 0, 0, 0], # "Uostalom, snimio je Blade Runner 2049, nastavak kultnog filma Ridleya Scotta, a što je, vjerujem, bio također iznimno zahtjevan zadatak kojeg je, srećom, uspješno položio."
    [0, 0, 0, 0, 0],  # "Da se Villeneuve odlično snalazi u SF žanru, dokazao je i s filmom “Arrival”, jednim od najboljih filmova u zadnjih nekoliko godina."
    [1, 1, 1, 1, 0], # "No, čini se kako je sve to bila samo priprema za “Dune”, daleko najzahtjevniji projekt u njegovoj karijeri."
    [1, 0, 1, 0, 0], # "Ono što je u mojim očima činilo Villeneuvea idealnim izborom za ekranizaciju Herbertovog romana svakako je njegov stil režije, a koji itekako odgovara svijetu pješčanog planeta."
    [1, 0, 1, 1, 0], # "Tu prvenstveno mislim na suptilnost u stvaranju napetosti, odnosno testiranje strpljivosti gledatelja koja se na kraju uvijek isplati."
    [1, 0, 1, 0, 0], # "Da je tome tako, pokazao je i s prvim filmom u kojem je njegovo bildanje tenzije, odnosno stvaranje priče kroz upoznavanje s likovima, poslužilo kao savršena predigra za sve ono što nas je dočekalo u nastavku."
    [1, 1, 1, 0, 1], # "Početak filma ponovno nas vodi na pješčani planet, gdje nastavljamo pratiti sudbinu likova kroz koje se doslovno osjeti Villeneuveova posvećenost detaljima, a što samu priču čini intimnijom, punom života."
    [0, 0, 1, 0, 0], # "Imam dojam kako kroz svaki lik doslovno možemo vidjeti redateljevu viziju “Dine” koja djeluje poput simfonije."
    [1, 1, 0, 1, 0], # "Ljudska lica jako su bitna za Villeneuvea, a što se najviše ocrtava kroz njihovu simbiozu s pejzažima."
    [1, 1, 0, 1, 0], # "Lica su u filmu poput krajolika koji se mijenja(ju) prema svjetlu sudbine koja ih prati na zajedničkom putovanju."
    [0, 0, 0, 0, 0], # "Sve to stvara kod gledatelja uzbuđenje i iščekivanje, kao da čitamo knjigu zamišljajući slike koje nam se ostvaruju na velikom platnu."
    [1, 0, 0, 0, 0], # "Stvarni krajolici još više naglašavaju prirodnost likova."
    [1, 0, 1, 1, 0], # "Tako i mi počinjemo vjerovati u privlačnost izazova s kojima se suočavaju."
    [0, 0, 0, 0, 0], # "Potencijal u razvoju ljudskog mozga bila je i Herbertova nit vodilja kroz romane, a upravo to i nama radi Villeneuve – tjera nas na razmišljanje, jednako kao i svoje likove."
    [0, 0, 1, 0, 0], # "“Dune: Part Two” je film u kojem i obično hodanje na pijesku djeluje poetično."
    [0, 0, 0, 0, 0], # "No, ni u jednom trenutku nisam osjetio kako Villeneuve teži nekom savršenstvu."
    [0, 0, 0, 0, 0], # "Dapače, čini mi se kako nesavršenost, simbolično prikazana kroz pukotine pijeska kroz koje reflektiramo svjetlost, zapravo najbolje prikazuje život."
    [0, 0, 0, 1, 1], # "Da, život koji je uvijek jači."
    [0, 0, 0, 0, 0], # "Ta (ne)savršenost čini svijet Dine ljudskim."
    [1, 0, 0, 0, 0], # "To je priča o čovječanstvu ispričana u budućnosti, i to kroz teme koje je Herbert obrađivao na jednako dojmljiv način u svojim romanima, počevši od miješanja vjere i politike, preko moći umjetne inteligencije pa sve do opasnosti koju sa sobom nosi kult karizmatičnih vođa, pardon, proroka."
    [1, 0, 1, 0, 0], # "Danas su te teme relevantnije nego ikada prije i Villeneuve je toga itekako svjestan, a što se najbolje vidi upravo kroz glavni lik filma – Paula Atreidesa."
    [1, 1, 1, 1, 1], # "Uloga budućeg “Mesije” pripala je Timothéeu Chalametu i prije nego se osvrnem na njegov lik u filmu imam potrebu nešto posebno naglasiti."
    [0, 0, 1, 0, 0], # "Dakle, bez ikakve dileme, za mene je Chalamet najbolji mladi glumac današnjice."
    [0, 0, 0, 0, 0], # "Kao netko tko je pogledao baš sve njegove filmove, ne mogu se načuditi koliko se podcjenjivački gleda na njegovu dosadašnju karijeru."
    [0, 0, 1, 0, 0], # "No, svatko tko je gledao film “Call Me by Your Name”, posebice zadnjih desetak minuta, nije mogao ne primijetiti koliki se glumački potencijal krije u njemu."
    [0, 0, 1, 0, 0], # "Da može odigrati i drugačije uloge, van nekakvih klišej uloga teenagerskog ljepotana, dokazao je i u filmu “Bones and All”, a bogami i u ovom nastavku filma “Dune” kojeg doslovno nosi na svojim leđima."
    [1, 1, 0, 1, 0],  # "Način na koji gledamo njegov lik u velikoj mjeri oslikava način na koji gledamo svijet Dine."
    [1, 1, 0, 1, 0],  # "Naime, prvi film i jest bio “nježni uvod” u sve ono što nas očekuje."
    [1, 1, 0, 1, 0],  # "Na isti smo taj način (do)živjeli i Paula, jer smo iznad njegovih ramena, metaforički rečeno, i otkrivali planet."
    [0, 0, 1, 1, 1],  # "Drugi dio, pak, puno je mišićaviji, snažniji, moćniji, jednako kao i Paul."
    [0, 0, 1, 0, 0],  # "Paul je za mene svakako najzanimljiviji lik u filmu, i to zahvaljujući upravo Chalametovoj izvedbi."
    [1, 1, 0, 1, 0],  # "I dok smo ga u prvom filmu doživljavali kao heroja, ovdje je Villeneuve suptilno dao do znanja kako on i nije baš toliki pozitivac kao što se čini, a što je opet na tragu i samog Herberta koji je u romanu dao neku vrstu upozorenja što se događa kada netko ima preveliku moć."
    [1, 1, 0, 1, 1],  # "Upravo je zbog toga i napisao roman “Mesija Dine”, a kojeg Villeneuve također planira ekranizirati."
    [1, 1, 0, 1, 1],  # "U tom smislu nam, baš poput nekog teasera, kroz neke dijelove filma daje naznaku kako bi taj treći dio ove sage mogao izgledati."
    [0, 0, 1, 0, 0],  # "Timothee je savršen za ovu ulogu, njegove aristokratske crte lica doslovno odaju inteligenciju u očima, jednako kao i ranjivost, mladost, a što mu kasnije dođe kao savršeno oružje u borbi s vlastitim identitetom."
    [1, 1, 0, 1, 1],  # "I kako idemo dalje, duboko u pijesak Dine, tako pratimo Paula koji traži osvetu, rastrganog između velike ljubavi i sudbine koja mu je namijenjena i za koju zna da dolazi."
    [1, 1, 0, 1, 0],  # "Ovo je priča o njegovom putovanju prema moći, gdje vidimo drugačiju, snažniju stranu njegovog lika, sliku vođe koju većina vidi u njemu."
    [1, 0, 0, 1, 0],  # "Istovremeno, svima onima koji sumnjaju u njega, odlučan je pokazati kako su u krivu."
    [1, 1, 0, 1, 0],  # "Simbolično se to može prenijeti i na samog Timothéea, posebice kroz jedan njegov moćan urlik kojim kao da se obraća skepticima ispred velikog platna: “Tišinaaaa!!"
    [1, 1, 0, 1, 1],  # "“Ovo je tek početak."
    [0, 0, 0, 0, 0],  # "Riječi s kojima završava prvi film na najbolji mogući način dokazuje kako je sve ono što smo gledali u njemu bilo tek obećanje koje je ispunjeno u nastavku."
    [1, 1, 0, 1, 0],  # "I ako je prvi film bio vođen kroz strah, ovaj je vođen borbom za moć."
    [0, 0, 1, 0, 0],  # "Osim toga, ovo je puno veći film u svakom mogućem pogledu, prvenstveno u glumačkom."
    [1, 1, 1, 1, 1],  # "Osim što samom pričom zadire u Herbertov svijet, upoznaje nas još intimnije s likovima koje smo imali priliku samo na kratko vidjeti u prvom filmu."
    [1, 1, 0, 1, 0],  # "Tu prvenstveno mislim na Chani (Zendaya) čiju smo prisutnost mogli osjetiti većinom kroz Paulove snove."
    [1, 1, 1, 0, 0],  # "Njena puno veća prisutnost čini od nastavka puno emotivniji film, posebice kroz njen odnos s Paulom."
    [0, 0, 0, 1, 0],  # "Međutim, Chani je ovdje puno više od ljubavnog zanosa za Paula."
    [0, 0, 0, 0, 0],  # "Ona ga najviše i izaziva, takoreći njegov je vodič, doslovno i figurativno, te dominira velikim platnom svaki put kad se pojavi."
    [1, 1, 1, 1, 1],  # "No, njega snaga ne očituje se samo kroz odnos s Paulom, već i kroz dijaloge s drugim likovima."
    [0, 0, 1, 0, 0],  # "Meni je, primjerice, bilo jako zanimljivo vidjeti na koji način mi osjećamo njene emocije, posebice kad se treba suočiti s nekim teškim životnim odlukama."
    [1, 1, 1, 0, 0],  # "Naime, tada je fokus isključivo na njenom licu, nema nikakvih dijaloga, sve što trebaš dobiti vidiš upravo u njenim očima."
    [0, 0, 0, 1, 0],  # "U očima joj je oslikana i budućnost, posebice ona koja je namijenjena Paulu, a koju zamišljamo baš kroz njen pogled."
    [0, 0, 0, 0, 0],  # "Kada su u pitanju ostali likovi, onda svakako treba izdvojiti Javiera Bardema, čiji je lik Stilgara također doživio transformaciju za koju smo se nadali da ćemo je vidjeti u nastavku, još za vrijeme gledanja prvog filma."
    [0, 0, 1, 0, 0],  # "Srećom, to se i dogodilo, jer Stilgar je lik koji najviše vjeruje u sve ono što je sudbinski zapisano za Paula."
    [1, 1, 1, 0, 1],  # "Nivo posvećenosti koju njegov lik ima za taj zadani cilj, gotovo je identična onoj koju je Bardem unio u portret svog filmskog lika."
    [0, 0, 1, 0, 0],  # "Ono što mi se također svidjelo kod njega svakako je suptilan humor kojeg koristi čak i u ozbiljnijim trenucima, kada samo jednom mimikom lica ili nekim odgovorom donosi svjetlo na pijesak Dine."
    [0, 0, 1, 0, 0],  # "Njegova emocija i strast u ono što vjeruje doslovno vas tjera da istovremeno osjećate strah zbog mogućeg ispunjenja proročanstva, ali i sreću što postoji takav lik u filmu."
    [0, 0, 0, 0, 0],  # "Rebecca Ferguson kao Lady Jessica također je dobila prirodan razvoj u ovom filmu, a koji nije bitan samo za njen lik, već i za ostale članove sestrinstva “Bene Gesserit”."
    [0, 1, 1, 0, 1],  # "Putovanje Lady Jessice otvorilo je tako prostor za još neke likove, poput primjerice za Lady Margot Fenring koju je portretirala meni posebno predivna Lea Seydoux."
    [0, 0, 0, 0, 0],  # "No, dok ćemo, nadajmo se, više od njene priče dobiti u trećem filmu, Lady Jessica s druge strane se još jednom pokazala kao intrigantan lik, puno kompleksniji nego u prethodniku, dok sama njena pojava diše dozu privlačne mitologije."
    [0, 0, 0, 0, 0],  # "Od likova koje smo upoznali u ovom nastavku, moram priznati kako me najviše privukla Florence Pugh koja je kao princeza Irulan oživjela duh onog starog Hollywooda kada su slični likovi imali tu jednu neopisivo magičnu eleganciju, i čija je pojavnost bila dovoljna za divljenje."
    [1, 1, 0, 0, 1],  # "U tom smislu treba promatrati i značaj koji ima prema “Caru” (Christopher Walken)."
    [1, 1, 0, 0, 0],  # "Car je uvijek bio u pozadini same priče, no kao i takav izaziva naše poštovanje."
    [1, 1, 1, 1, 1],  # "U njegovom pogledu može se osjetiti nesigurnost, baš prigodno za nekoga tko je prepun žaljenja."
    [1, 1, 1, 1, 0],  # "Naravno, on tu slabost pokušava sakriti, a u tome mu itekako pomaže Irulan, odnosno njega snaga koja djeluje kao ravnoteža njegovoj ranjivosti."
    [1, 1, 1, 1, 1],  # "Ne znam da li bih se trebao zabrinuti što sam se prilikom prvog upoznavanja s planetom Dine najviše zainteresirao za kuću Harkonnen, posebice ako pogledate baruna Vladimira, u prvom filmu u izvrsnoj interpretaciji jednog od najvećih glumaca Stellana Skarsgarda, a koji je odbojan na svaki mogući način."
    [0, 0, 1, 0, 0],  # "Pa ipak, opet me nekako uspio sadistički privući, dovoljno da se zainteresiram za njega, bez obzira na posljedice."
    [0, 0, 1, 0, 0],  # "No, da sam imao dobar osjećaj kako me Harkonneni, barem u smislu dosade, neće razočarati, dokazao je i lik s kojim smo se upoznali upravo u ovom nastavku."
    [1, 1, 0, 1, 2],  # "Riječ je, dakako, o Feydu-Rauthu kojeg je utjelovio neprepoznatljivi Austin Butler."
    [0, 0, 1, 1, 0],  # "Harkonneni, ma koliko god bili izopačeni, imaju u sebi tu neki sofisticiranost, barem meni."
    [0, 0, 1, 1, 0],  # "Istina, ona je psihotična, ali im nitko ne može oduzet činjenicu kako su upravo oni najnapredniji, a što stvara ubitačnu kombinaciju."
    [0, 0, 1, 0, 0],  # "To je najbolje vidljivo upravo na Feydu-Rauthu, a koji je pronicljiv, lukav, sexy, suptilan baš poput one otrovne oštrice."
    [0, 0, 1, 0, 0],  # "Karizmatičan, inteligentan, taktičar i uz sve to nemilosrdan."
    [1, 1, 0, 1, 0],  # "Zapravo, sve ovo navedeno stane u onom njegovom prodornom životinjskom pogledu."
    [1, 0, 0, 0, 0],  # "No, čini se kako i Villeneuve dijeli moju zainteresiranost prema Harkonnenima, s obzirom na to da je upravo kroz baruna Vladimira odao počast “Dini”, Davida Lyncha."
    [0, 0, 1, 0, 0],  # "Ljubitelji tog filma lako će prepoznati taj uistinu lijep filmofilski trenutak."
    [0, 0, 1, 0, 0],  # "U vizualnom smislu film je prava poslastica ne samo za ljubitelje znanstvene fantastike, već i filmova općenito."
    [0, 0, 1, 0, 0],  # "Ono što su “Infinity War” i “Endgame” bili za superjunačke filmove, ono što je trilogija “Gospodar prstenova” za fantasy žanr, to je ovaj film za SF."
    [0, 0, 1, 0, 0],  # "Sve je savršeno, počevši od kostima, scenografije, glazbe, zvuka, montaže i vizualnih efekata..."
    [0, 0, 0, 0, 0], # "Jer, da su se kojim slučajem našli u konkurenciji u bilo kojoj kategoriji, posebice kada su u pitanju one tehničke, imali bi manje šanse nego Lloyd prema Marry u filmu 'Glup i Gluplji'."
    [0, 0, 1, 0, 0], # "Zvuk bih također posebno istaknuo, jer je itekako bitan za sam doživljaj i zato nije ni čudo što je Villeneuve inzistirao da se film doživi na najvećem mogućem platnu."
    [0, 0, 1, 0, 0], # "Da, vizuali su prekrasni, ali zvuk je ono što ovaj film čini posebnim."
    [0, 0, 0, 0, 0], # "Svaki kadar djeluje kao da je dizajniran po određenom dobu dana, posebno kroz paletu boja koje su privlačne jer služe samoj priči."
    [0, 0, 1, 0, 0], # "Da, predivnoj priči za koju imam osjećaj kao da je putovala kroz vrijeme te se vratila ponovno k nama."
    [0, 0, 1, 0, 0], # "Svi u filmu imaju neki poseban izgled, pa čak i kada su u pitanju pojedine bitke, doslovno ništa nije prepušteno slučaju."
    [1, 1, 0, 0, 0], # "Najbolji primjer za to je bitka ispod mjesečine, a koja je u potpunosti crno-bijela."
    [0, 0, 1, 0, 0], # "Ti kadrovi borbe uistinu su bili nešto posebno upravo zato što su ukomponirani u širi kontekst filma."
    [0, 0, 1, 0, 0], # "Također, borbe jedan na jedan, posebice u završnici, brzina i koordinacija pokreta u njima, naprosto zadivljujuće."
    [0, 0, 1, 0, 0], # "Villeneuve, barem je takav moj dojam, svaki film snima tako da ih možemo gledati zasebno i svejedno uživati u njima."
    [1, 0, 0, 0, 0], # "Ne opterećuje se previše s onim što donosi budućnost, bez obzira na to što kod njega postoji želja za snimanjem još jednog filma koji bi zaokružio cijelu trilogiju, a što i mućki pokazuje ubacivanjem nekih teasera, dovoljno da zaintrigira publiku."
    [2, 2, 2, 2, 2], # "I u tome zapravo može nastati problem kod nekih gledatelja."
    [1, 2, 2, 2, 2], # "Naime, malo koja trilogija ima filmove koji se mogu gledati zasebno, bez razmišljanja o ostalim naslovima."
    [1, 1, 0, 1, 1], # "Jedina koja mi možda pada na pamet je originalna 'Star Wars' trilogija."
    [0, 0, 1, 0, 0], # "U tom smislu treba reći kako bi prvi Dune film bez ovog nastavka i dalje bio dobar film, ali zar ne bi bila šteta da je ostalo samo na tome."
    [1, 1, 1, 1, 1], # "S druge strane, koliko god tražio još od same priče, a što je itekako opravdano zbog brojnih likova, moram priznati kako ne bih bio previše razočaran i da s ovim nastavkom zaključimo priču."
    [1, 1, 1, 0, 0], # "Ali opet, nekako mi prevladava (znati)želja, tako da se osjećam poput onog pustinjskog miša Muad’Diba koji stalno kopa po onom pijesku, pa zašto onda i ne pronaći još jedno uzbudljivo poglavlje svijeta Dine."
    [1, 0, 1, 0, 0], # "'Dune: Part Two' je film kroz koji nam je Denis Villeneuve uistinu ponudio kino iskustvo za pamćenje, poput kakvog arheologa koji je skinuo prašinu sa svih tih genijalnih ideja i tema koje je prije više od pola stoljeća stvorio veliki Frank Herbert te ih ponovno vratio u život."
    [0, 0, 1, 0, 0], # "Dugo mi se nije dogodilo da nakon odjavne špice ostanem sjediti u kinu, onako sa svojim mislima na ono što sam upravo doživio."
    [1, 1, 0, 1, 0], # "Pao mi je tada na pamet citat velikog Godarda koji je rekao kako će se partneri koji ne vole iste filmove kad tad rastati."
    [1, 1, 0, 1, 1], # "Naravno, redateljska gromada je govorila u metaforičkom smislu, misleći na pogled na teme koje neki filmovi obrađuju."
    [1, 2, 2, 2, 2], # "I zato, iskreno govoreći, teško bih se mogao zamisliti ne samo u odnosu, nego čak i u prijateljstvu s nekim tko, primjerice, ne cijeni film kao što je ovaj."
    [0, 0, 1, 0, 0], # "Jer, ovo je film koji nas tjera na razmišljanje o životu i koji nas podsjeća zašto volimo filmove i koliko moćna i snažna umjetnost može biti."
    [0, 0, 1, 0, 0], # "Ovaj film je razlog zbog kojeg postoje kina i baš zato ga trebate živjeti i osjećati, i to kroz magične pokretne slike koje nikada neće biti izgubljene u pijesku vremena."
])
ratings, _ = irr.aggregate_raters(ratings_raw)
kappa = irr.fleiss_kappa(ratings, method='fleiss')
print("Aggregated Ratings Matrix:\n", ratings)
print("Fleiss' Kappa: {kappa:.4f}")
